### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by PiscesdanAT** [wolforcept/hearthwell#1]
Mod Version: 0.0.1
JEI Version: 1.12.2-4.13.1.225
Forge Version: 1.12.2-14.23.5.2768

Crash Report: [Link](https://pastebin.com/KWxRLRYd)

**Comment by wolforcept** [comment]
Hopefully this is fixed in version 0.0.2.
Ill wait for you to confirm it and will close this afterwards.
Thank you for your time.

**Comment by PiscesdanAT** [comment]
It did work. Wonderful. Thank you.
