### ISSUE TITLE
.json issue

### ISSUE THREAD

**Issue by brachy84** [wolforcept/hearthwell#12]
There is a custom recipe file issue in hwell 0.2.1 when i launched minecraft with 0.2.1 the log say the json is to old (or something like that). So I copied my custom core and deleted the file. Started minecraft to generate a new json file. But this json contains syntax issues. 
1. At the a "}" is missing
2.something with seed of life recipe

**Comment by wolforcept** [comment]
Post your file and also delete it completely and restart the game
