### ISSUE TITLE
Crash when you drop an item into an random portal.

### ISSUE THREAD

**Issue by knoxhack** [wolforcept/hearthwell#14]
Crash when you drop an item into the portal, works fine with items added via CT scripts.

Crash:
https://paste.dimdev.org/remuxacuje.mccrash

Modpack:
Version: 1.6.1

**Comment by GrokDuckFarmer** [comment]
I'm getting a very similar error when an item is tossed into a Nether portal.  In this case, a pigman was killed, and some rotten flesh flew into the portal.  Tossing crystals into the portal works just fine.

Hearth Well version:  0.3

https://pastebin.com/J65LRLPK

**Comment by wolforcept** [comment]
This was fixed in 3.1 correct? When confirmed i will close the issue
