### ISSUE TITLE
[Suggestion] Coring CraftTweaker Support

### ISSUE THREAD

**Issue by ghost** [wolforcept/hearthwell#19]
It would be very useful if there was some basic CraftTweaker support for the coring blocks. I'm creating a modpack that includes Hearthwell, and i'd love to include the coring blocks in the progression, but at the present (as best as I can tell) there is no way for me to remove any of the coring recipes. So either I must break my progression or disable the coring block/s outright. I understand if you don't want to add the ability to create _new_ coring blocks because of the animations, but at a bare minimum being able to add and remove recipes from the current core blocks would be very helpful.

In any case keep up the good work; this is a neat mod.

**Comment by wolforcept** [comment]
Hello there! The coring recipes, as everything else, are configurable through a json file, that you must enable in the basic config.
You can even create your custom cores, with custom colors and recipes. 
Crafttweaker support for cores is a little harder to do but is in the horizon anyway. 
I would suggest joining the hearth well discord for real time information and help.
