### ISSUE TITLE
Missing oredict for ingots and gems

### ISSUE THREAD

**Issue by Lykrast** [wolforcept/hearthwell#20]
Several mods rely on oredict tags to detect and make use of ingots and their other forms (like Tinkers Construct if someone wants to add your materials to it, and maybe the Immersive Engineering Arc Furnace for recycling). So the following oredicts entry should be added:

* `ingotHeavy`, `nuggetHeavy` and `blockHeavy` for the Heavy Ingot and derivatives
* `ingotSoulsteel`, `nuggetSoulsteel` and `blockSoulsteel` for Soulsteel
* `ingotAsul`, `nuggetAsul` and `blockAsul` for Asul
* `ingotMysticIron` (or `ingotIronMystic`, as you want) and the rest for Mystic Iron
* `ingotMetaldiamond` and `blockMetaldiamond` for Metaldiamond

I would suggest something for Crystals and Nether Crystals, but since they have a very generic name I don't know what would be a good way around that (they would need `gemXXX` and `blockXXX`).

Some also could be added for the stones, like `stoneAzurite` or `stoneBrackish`. Although that's not as important it's still nice to have.

Also **PLEASE** register oredict right after registering items in the registry event instead of late during Init.

**Comment by ghost** [comment]
salt, as well

**Comment by Lykrast** [comment]
It's in the latest version so it very likely got fixed earlier. Closing the issue.
