### ISSUE TITLE
Heat Furnace not respecting input block metadata when smelting.

### ISSUE THREAD

**Issue by jaynesb** [wolforcept/hearthwell#21]
Forge: 14.23.5.2838
Hearth Well: 0.4.1

I've noticed that when tossing ores or blocks that use metadata to differentiate their types into the Heat Furnace, the output is the same regardless of which ore was tossed into the furnace.

For example, if I toss lead ore from Thermal Foundation (thermalfoundation:ore:3) into the Heat Furnace, I get a copper ingot, as if I had tossed in a copper ore (thermalfoundation:ore:0).

**Comment by wolforcept** [comment]
Thank you for this, has been fixed and will be out in the next version.
