### ISSUE TITLE
Crash Bug - 0.3.1 - Fertile Soil + Cocoa Pod = Crash on Dimension Load.

### ISSUE THREAD

**Issue by Hosed** [wolforcept/hearthwell#22]
I'm using Version 0.3.1 in the Mystical Skies modpack (version 1.7.1 of the pack) so this bug may no longer be present, but since it was a world corrupting issue I'm posting it anyways.

Reproduction is fairly simple.  I placed a Jungle Wood block next to some Fertile Soil and then planted a cocoa bean on the wood, directly over the fertile soil.  When the bean had reached full growth my world crashed and became corrupted with an "Invalid Property" exception from the Fertile Soil.

Using MCEdit, I deleted the single Cocoa Bean and the world loaded correctly again.

**Comment by wolforcept** [comment]
Oh wow thank you. I supposed it hasnt been fixed yet since i never experienced anything similar

**Comment by wolforcept** [comment]
Thank you for this, has been fixed and will be out in the next version.
