### ISSUE TITLE
Heat Furnace self sets on fire & destroys items

### ISSUE THREAD

**Issue by VallenFrostweaver** [wolforcept/hearthwell#23]
When you have assembled the heat furnace, the lava source blocks in it will still randomly set the opening on fire which in turn destroys your items you are putting in it.

Using it in the Mystical Skies modpack: 1.7.1
Hearth Well: 0.3.1
Forge: 14.23.5.2825

**Comment by wolforcept** [comment]
Never thought that the fire was cause by the Tube and not by the Heat Block, but that was what was happening, so its been fixed and will be out in the next patch.
