### ISSUE TITLE
Suggestion: Book of the Well multiblock ingredients list

### ISSUE THREAD

**Issue by VallenFrostweaver** [wolforcept/hearthwell#24]
An ingredients list of the base items needed to build a multiblock structure would be nice. For example of issues it may solve, you can't always tell what the item is in the image and may place the wrong item. While the patchouli placed hologram will tell you what the items are when you look at them with The One Probe or WAILA installed it only tells you the blocks that have a surface below them already and you don't know if you have the right materials to build the structure until you are already trying to build it. This feature request may already exist and I overlooked it. In that case, just close this out but please let me know where this info is before you do. :)

**Comment by wolforcept** [comment]
Thanks for reminding me (this was on my todo list for three thousand years).
