### ISSUE TITLE
Living Branches decay to dead branches after Minecraft crashes

### ISSUE THREAD

**Issue by codewarrior0** [wolforcept/hearthwell#25]
This happens because the Living Branches use the system clock for their decay timer. Seriously, don't do that.

hwell-0.4.1.jar
Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2

**Comment by wolforcept** [comment]
I could easily make them use mc time. That was not the purpose though. Isnt that explained in the book?

**Comment by wolforcept** [comment]
It is.
