### ISSUE TITLE
Neither JSON nor CraftTweaker seems to recognize damage data

### ISSUE THREAD

**Issue by DestinyPlayer** [wolforcept/hearthwell#26]
Specifically, I am trying to do things such as adding Puller recipes for <nuclearcraft:ore:5> and Tube recipes for things like <libvulpes:ore0:8> and other such things. The problem being, neither block seems to recognize the damage number, neither in the json file with "data":8, nor in CraftTweaker via regular :8. Am I doing something wrong?

In addition, it doesn't seem like the CT Puller recipes work period, even with blocks that aren't damage-based.

Here's my CT file - https://paste.dimdev.org/ucogitelef.xml
Here's my hwell_recipes.json file - https://paste.dimdev.org/owiceyuwoy.json

Edit: finally remembered the proper name for the thing.

**Comment by wolforcept** [comment]
Whats the behaviour? Is the data simply ignored?

**Comment by DestinyPlayer** [comment]
Yes. It shows up correctly in JEI, but the actual process assumes all of them as input, and utilizes the first of them as output. That way, every single nuclearcraft:ore block, no matter the data, gets turned into Copper Ore, regardless of what it's supposed to be data-wise.

**Comment by DestinyPlayer** [comment]
Additional bug: the Heat Furnace also has issues with these data bits. I just threw in two tin dusts, and ended up with two copper ingots instead.

**Comment by wolforcept** [comment]
Seems that its fixed.
