### ISSUE TITLE
[BUG] Crash when a Clicker from "Click Machine" breaks a Dust Picker

### ISSUE THREAD

**Issue by DestinyPlayer** [wolforcept/hearthwell#27]
So, basically that. I designed a system to automate the production of shards via Dust Pickers. The only issue, apparently the Click Machine doesn't like when a Dust Picker breaks.

https://paste.dimdev.org/lewuliyazo.mccrash - crash log
https://cdn.discordapp.com/attachments/495788307775488050/594543382634823680/unknown.png - the machine itself
http://prntscr.com/o8br8t - the modpack

Hearth Well version - 0.4.1
Click Machine version - 1.2.0
Forge - 14.23.5.2838

**Comment by wolforcept** [comment]
Huh okay. Seems to be a simple issue to solve. Will fix asap
