### ISSUE TITLE
Tall grass spam on fertile soil

### ISSUE THREAD

**Issue by wizard1399** [wolforcept/hearthwell#28]
Fertile soil spams tall grass when it is placed on it. 
Steps to reproduce:
Place fertile soil.
Grab grass from decoration tab.
Place decorative grass on fertile soil.

Grass grows to talk grass version. After growing to the tall version, it will start spamming an item called
minecraft:double_plant

After further testing this happens with all 2high plants from the decoration tab.

**Comment by wolforcept** [comment]
Yes, i know, but thanks. I even used this to my advantage, cause i dont know how to fix it

**Comment by wizard1399** [comment]
How did you use it? I must have missed that part in the book.

**Comment by wizard1399** [comment]
Do you check the block above the soil before a growth tick is applied? The list of 2 tall plants has only 7 items. Any chance that blacklisting these items as part of an if statement would work?

**Comment by wolforcept** [comment]
Huh, maybe ill do that

**Comment by wolforcept** [comment]
Thank you for the idea. Its not spamming now :)
