### ISSUE TITLE
Molten fluids pls!

### ISSUE THREAD

**Issue by wizard1399** [wolforcept/hearthwell#29]
Could you add a fluid version of your metals? This would be useful for cross mod comparability. Several mods add forms of melting either the ore or the ingot to form the metal into the needed shape. Little things like this make a mod more playable for pack makers.

**Comment by wolforcept** [comment]
Hello. I dont like adding things to the mod that have no purpose, but there are a couple of mods that will add custom fluids of materials, and you might use those to get the molten metals?

**Comment by wizard1399** [comment]
Sorry, I just saw this post. It is not a matter of adding things that are not used, it is giving modpack developers what they need so that your mod plays nice in a pack. Several other mods do this including Twilight forest.
