### ISSUE TITLE
Can see through solid blocks with Mysterious Leaves

### ISSUE THREAD

**Issue by Lykrast** [wolforcept/hearthwell#34]
As seen here, you can see through solid blocks if using Mysterious Leaves.

![image](https://user-images.githubusercontent.com/8684850/61588413-4fe1f600-ab9b-11e9-81c5-5d0f9cc21257.png)
![image](https://user-images.githubusercontent.com/8684850/61588417-64be8980-ab9b-11e9-9aca-863d641fc708.png)

**Comment by wolforcept** [comment]
Thank you for this, has been fixed and will be out in the next version.
