### ISSUE TITLE
[Suggestion] JEI support for the Charger and Ore Puller

### ISSUE THREAD

**Issue by Lykrast** [wolforcept/hearthwell#35]
Since the Charger sometimes returns items (like Empty Rods when throwing Myst Rods) it would be nice to have JEI support for it, also showing how much power each item is replenishing.

As for the Ore Puller, it would be a very nice touch, something a bit similar to Environmental Tech. It would also allow to see what shards filter what ores.

**Comment by wolforcept** [comment]
Thank you for this, has been fixed and will be out in the next version.
