### ISSUE TITLE
Crushing Blocks Doesn't give output for all items in the ground

### ISSUE THREAD

**Issue by Fireztonez** [wolforcept/hearthwell#36]
Hello,
I just try to trough 64 gravel in the ground place the Crushing Block on top, question of craft all the flint, but I get only 2 flint and doesn't get any gravel back... So It look like all the rest is completely void.

I test that on server, doesn't try in single player yet.

Version:
Hearth Well: 0.4.2
Minecraft Forge: 14.23.5.2838

**Comment by wolforcept** [comment]
Hello. The crushing block recipe for flints does not have a guaranteed output, hopefully it will be more clear when the next update arrives with changed to JEI integration.
