### ISSUE TITLE
Some JEI categories have icons with the wrong rotation

### ISSUE THREAD

**Issue by Lykrast** [wolforcept/hearthwell#37]
The left slot of the Separator and all slots of the Freezer in JEI have the wrong rotation/shading which makes them look really off.

![image](https://user-images.githubusercontent.com/8684850/61870738-26003a80-aedf-11e9-9003-a16079136656.png)
![image](https://user-images.githubusercontent.com/8684850/61870766-344e5680-aedf-11e9-86f5-04a56229649b.png)

**Comment by wolforcept** [comment]
Thank you for this, has been fixed and will be out in the next version.
