### ISSUE TITLE
Getting Book doesn't work

### ISSUE THREAD

**Issue by Dragnier** [wolforcept/hearthwell#39]
I've tried several times to get the book the way it is mentioned on the wiki, but it doesn't work.

**Comment by wolforcept** [comment]
Hello there! Some modpacks have it disabled. Or you might be doing something slightly wrong, one never knows. You can hop by the hearth well discord and post some screenshots. Me or anyone else there will probably answer them!

**Comment by Dragnier** [comment]
I literally downloaded it just to try adding it to a pack I was making. I typed what it said to type and then immediately right-clicked with the two wooden pressure plates in hand/offhand while looking straight up the whole time. I even tried sneak-right-click because the wiki mentions sneaking. I tried about 10 times; nothing happened. I shouldn't need a manual to learn how to obtain the manual...

Fun fact: you can't stay sneaking and type. The second you hit T to open the chat, you un-sneak.

I've since remove this mod. While the crafting seems unique, I cannot understand why such a convoluted method was instituted to obtain the instruction manual. It's just counter-intuitive. If you want people to use your mod, said instruction manual should be easy to get or simply provided. If I do use it at some point, I'll most likely provide an alternate crafting recipe for said manual...

**Comment by wolforcept** [comment]
I'm very sorry you couldn't get the book. The mod needs patchouli installed so that the book is available. Also your prayer cant just be the words, it has to have spmething else.
I hope you reconsider and try the mod! Thank you

**Comment by wolforcept** [comment]
If you have any other trouble you can always pop by the Hearth Well discord for much quick responses from me and the community!
