### ISSUE TITLE
No Method for obtaining Mushrooms/Mycelium/Nether wart

### ISSUE THREAD

**Issue by TyreForHyre** [wolforcept/hearthwell#42]
As far as I can tell all of these are unattainable in a stone/skyblock setting without access to the nether,
Version 0.5.1 of Hearth Well

**Comment by wolforcept** [comment]
Mushroomsl blocks and mycelium were obtainable through coring i think? Are they not anymore? If not that must be fixed. 
Nether warts were obtainable through mutation right? The recipe must have been lost when converting to the mutator recipes. 
thank you, will look into it

**Comment by TyreForHyre** [comment]
Mushrooms blocks and mycelium -are- attainable through coring, but can't get a mushroom block without mycelium (or feeding it a mushroom block to start with) and can't get mycelium without a mushroom block (or feeding it a mushroom block to start with). Kind of a chicken or the egg cyclical situation. I thought maybe at least small mushrooms would spawn with the nether seed but no dice.

**Comment by wolforcept** [comment]
Oh I see. Will solve as soon as I can. Sorry.

**Comment by wolforcept** [comment]
Fixed this, will be out in HW 0.5.3
