### ISSUE TITLE
Burst seeds sometimes send their items through other blocks nearby

### ISSUE THREAD

**Issue by Master00Maniac** [wolforcept/hearthwell#47]
Tested with various burst seeds in the 0.4.2 version, in a 5x5x3 room. Item entities could easily be fired through the floors and walls of the room from most positions within the room

The walls were made of solid cobblestone, with the exception of one block replaced with a gravity block. Double layering the walls helped, but a few items still slipped through. The floors weren't an issue afterward though (as I simply filled in the floor to ground level).

**Comment by wolforcept** [comment]
Hello. This is kind of a problem with Minecraft itself, since the items are thrown at really high speeds. Sorry.

**Comment by Master00Maniac** [comment]
EDIT: my bad, wrong bug report
