### ISSUE TITLE
[Request] Make Grafter accept external fluid connectors for liquid souls. 

### ISSUE THREAD

**Issue by Garnin** [wolforcept/hearthwell#52]
I've tried IE pipes as well as Ticon Channels which I've never had problems with before, I've even tried connecting to different sides. This leads me to believe the functionality hasn't been implemented yet so I'm requesting it. I love the mod, and with some clever craftweaking(depending on the desired difficulty) I think it could fit into nearly any modpack that includes magic.

**Comment by Garnin** [comment]
I'd also like to add that it doesn't accept additional cores via a hopper either.

**Comment by wolforcept** [comment]
Hello. Thank you for taking interest in the mod.
Grafting is a process parallel to normal coring and its not suitable for automation and mass production. Its objective is to make it easier to get materials in relative large quantities without automation. Normal coring is, however, automatable. Crystal and shard production is not very well automatable at the moment but thats the part that will be worked on in the future. I might implement this that you are requesting maybe, but it will be disabled by default.
