### ISSUE TITLE
Book doesn't show Precision Grinder Multiblock [0.2]

### ISSUE THREAD

**Issue by PiscesdanAT** [wolforcept/hearthwell#7]
When looking at the Multiblock for the Precision Grinder in the Guidebook, it only displays a single block of cobblestone. This also happens when visualizing the structure in the world.

https://imgur.com/a/nSCLADY

Side note: The Tooltip for the block says that it only requires 5 Energy per operation instead of 100.

**Comment by wolforcept** [comment]
The book is still in the making and many things are placeholders.
The precision grinder only requires 5 energy, its the documentation that is not updated.

**Comment by wolforcept** [comment]
The book is still in the making and many things are placeholders.
The precision grinder only requires 5 energy, its the documentation that is not updated.

**Comment by PiscesdanAT** [comment]
My bad. Good to know.
