### ISSUE TITLE
Mysterious Trees only spawn if they have vision of sky.

### ISSUE THREAD

**Issue by Bluberry-Kat** [wolforcept/hearthwell#8]
Using version 0.2 with forge version 2815.
Tested in creative mode, mysterious fertilizer can only turn a sapling into a mysterious tree if the sapling has unobstructed vision to the sky.

If intentional, could I have a config option to disable it? I'm making a modpack in a similar manner to Stoneblock and requiring sky vision would be incredibly player unfriendly.

**Comment by wolforcept** [comment]
Done. Will come out in next bugfix patch.

**Comment by wolforcept** [comment]
I'm just messing with you :) thank you for playing my mod
