### ISSUE TITLE
Obsidian Displacer can't actually collect Grass, despite tooltip saying otherwise.

### ISSUE THREAD

**Issue by Bluberry-Kat** [wolforcept/hearthwell#9]
Using version 0.2 with forge version 2815.

I've tested the Obsidian Displacer on Obsidian _and_ Ice, and it seems to work fine. However, when holding right click to harvest grass, instead of the displacer being "pulled back," it does nothing, and thus, cannot collect grass.

**Comment by wolforcept** [comment]
![image](https://user-images.githubusercontent.com/11655959/53616298-d6407000-3bd9-11e9-99db-e28ba31ced2a.png)
this "grass" ?

**Comment by wolforcept** [comment]
I'm just messing with you :) thank you for playing my mod!

**Comment by Bluberry-Kat** [comment]
ah, i can't read

thank you, though ;p

**Comment by wolforcept** [comment]
The other displacer, the Empowered Displacer, works on grass though. In fact, it works on almost everything. Including Bedrock. Not even kidding.
